// ============
// Github Repos
// ============
var repoApi = [{
    "id": 19747171,
    "name": "kb-15-jQuery-Examples",
    "full_name": "kevbost/kb-15-jQuery-Examples",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-15-jQuery-Examples",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples",
    "forks_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-15-jQuery-Examples/releases{/id}",
    "created_at": "2014-05-13T16:40:28Z",
    "updated_at": "2014-05-14T06:56:55Z",
    "pushed_at": "2014-05-14T06:56:55Z",
    "git_url": "git://github.com/kevbost/kb-15-jQuery-Examples.git",
    "ssh_url": "git@github.com:kevbost/kb-15-jQuery-Examples.git",
    "clone_url": "https://github.com/kevbost/kb-15-jQuery-Examples.git",
    "svn_url": "https://github.com/kevbost/kb-15-jQuery-Examples",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19383110,
    "name": "kb-css-thirty-examples",
    "full_name": "kevbost/kb-css-thirty-examples",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-css-thirty-examples",
    "description": "5/2/15 - Second Project at the Iron Yard",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples",
    "forks_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-css-thirty-examples/releases{/id}",
    "created_at": "2014-05-02T17:42:14Z",
    "updated_at": "2014-05-06T20:53:24Z",
    "pushed_at": "2014-05-06T20:53:24Z",
    "git_url": "git://github.com/kevbost/kb-css-thirty-examples.git",
    "ssh_url": "git@github.com:kevbost/kb-css-thirty-examples.git",
    "clone_url": "https://github.com/kevbost/kb-css-thirty-examples.git",
    "svn_url": "https://github.com/kevbost/kb-css-thirty-examples",
    "homepage": null,
    "size": 668,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19316702,
    "name": "kb-day-two-hw",
    "full_name": "kevbost/kb-day-two-hw",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-day-two-hw",
    "description": "4/30/14 - Replicating an image as a real website.",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-day-two-hw",
    "forks_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-day-two-hw/releases{/id}",
    "created_at": "2014-04-30T14:40:39Z",
    "updated_at": "2014-05-02T17:09:02Z",
    "pushed_at": "2014-05-02T17:09:01Z",
    "git_url": "git://github.com/kevbost/kb-day-two-hw.git",
    "ssh_url": "git@github.com:kevbost/kb-day-two-hw.git",
    "clone_url": "https://github.com/kevbost/kb-day-two-hw.git",
    "svn_url": "https://github.com/kevbost/kb-day-two-hw",
    "homepage": null,
    "size": 5496,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19382636,
    "name": "kb-day-two-hw-rewrite",
    "full_name": "kevbost/kb-day-two-hw-rewrite",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-day-two-hw-rewrite",
    "description": "5/2/15 New repository for re-write of kb-day-two-hw",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite",
    "forks_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-day-two-hw-rewrite/releases{/id}",
    "created_at": "2014-05-02T17:25:34Z",
    "updated_at": "2014-05-02T17:36:22Z",
    "pushed_at": "2014-05-02T17:36:20Z",
    "git_url": "git://github.com/kevbost/kb-day-two-hw-rewrite.git",
    "ssh_url": "git@github.com:kevbost/kb-day-two-hw-rewrite.git",
    "clone_url": "https://github.com/kevbost/kb-day-two-hw-rewrite.git",
    "svn_url": "https://github.com/kevbost/kb-day-two-hw-rewrite",
    "homepage": null,
    "size": 4080,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19722783,
    "name": "kb-js-day-three",
    "full_name": "kevbost/kb-js-day-three",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-js-day-three",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-js-day-three",
    "forks_url": "https://api.github.com/repos/kevbost/kb-js-day-three/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-js-day-three/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-js-day-three/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-js-day-three/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-js-day-three/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-js-day-three/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-js-day-three/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-js-day-three/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-js-day-three/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-js-day-three/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-js-day-three/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-js-day-three/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-js-day-three/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-js-day-three/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-js-day-three/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-js-day-three/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-js-day-three/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-js-day-three/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-js-day-three/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-js-day-three/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-js-day-three/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-js-day-three/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-js-day-three/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-js-day-three/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-js-day-three/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-js-day-three/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-js-day-three/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-js-day-three/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-js-day-three/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-js-day-three/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-js-day-three/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-js-day-three/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-js-day-three/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-js-day-three/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-js-day-three/releases{/id}",
    "created_at": "2014-05-13T02:14:24Z",
    "updated_at": "2014-05-13T15:47:54Z",
    "pushed_at": "2014-05-13T15:47:54Z",
    "git_url": "git://github.com/kevbost/kb-js-day-three.git",
    "ssh_url": "git@github.com:kevbost/kb-js-day-three.git",
    "clone_url": "https://github.com/kevbost/kb-js-day-three.git",
    "svn_url": "https://github.com/kevbost/kb-js-day-three",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19596621,
    "name": "kb-js-day-two",
    "full_name": "kevbost/kb-js-day-two",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-js-day-two",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-js-day-two",
    "forks_url": "https://api.github.com/repos/kevbost/kb-js-day-two/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-js-day-two/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-js-day-two/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-js-day-two/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-js-day-two/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-js-day-two/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-js-day-two/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-js-day-two/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-js-day-two/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-js-day-two/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-js-day-two/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-js-day-two/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-js-day-two/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-js-day-two/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-js-day-two/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-js-day-two/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-js-day-two/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-js-day-two/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-js-day-two/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-js-day-two/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-js-day-two/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-js-day-two/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-js-day-two/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-js-day-two/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-js-day-two/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-js-day-two/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-js-day-two/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-js-day-two/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-js-day-two/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-js-day-two/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-js-day-two/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-js-day-two/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-js-day-two/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-js-day-two/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-js-day-two/releases{/id}",
    "created_at": "2014-05-09T02:44:36Z",
    "updated_at": "2014-05-11T23:15:39Z",
    "pushed_at": "2014-05-11T23:15:39Z",
    "git_url": "git://github.com/kevbost/kb-js-day-two.git",
    "ssh_url": "git@github.com:kevbost/kb-js-day-two.git",
    "clone_url": "https://github.com/kevbost/kb-js-day-two.git",
    "svn_url": "https://github.com/kevbost/kb-js-day-two",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19546341,
    "name": "kb-js-intro",
    "full_name": "kevbost/kb-js-intro",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-js-intro",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-js-intro",
    "forks_url": "https://api.github.com/repos/kevbost/kb-js-intro/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-js-intro/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-js-intro/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-js-intro/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-js-intro/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-js-intro/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-js-intro/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-js-intro/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-js-intro/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-js-intro/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-js-intro/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-js-intro/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-js-intro/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-js-intro/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-js-intro/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-js-intro/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-js-intro/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-js-intro/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-js-intro/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-js-intro/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-js-intro/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-js-intro/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-js-intro/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-js-intro/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-js-intro/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-js-intro/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-js-intro/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-js-intro/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-js-intro/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-js-intro/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-js-intro/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-js-intro/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-js-intro/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-js-intro/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-js-intro/releases{/id}",
    "created_at": "2014-05-07T18:55:19Z",
    "updated_at": "2014-05-09T00:32:11Z",
    "pushed_at": "2014-05-09T00:32:11Z",
    "git_url": "git://github.com/kevbost/kb-js-intro.git",
    "ssh_url": "git@github.com:kevbost/kb-js-intro.git",
    "clone_url": "https://github.com/kevbost/kb-js-intro.git",
    "svn_url": "https://github.com/kevbost/kb-js-intro",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}, {
    "id": 19464292,
    "name": "kb-scss-thirty-examples-rewrite",
    "full_name": "kevbost/kb-scss-thirty-examples-rewrite",
    "owner": {
        "login": "kevbost",
        "id": 1672548,
        "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
        "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
        "url": "https://api.github.com/users/kevbost",
        "html_url": "https://github.com/kevbost",
        "followers_url": "https://api.github.com/users/kevbost/followers",
        "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
        "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
        "organizations_url": "https://api.github.com/users/kevbost/orgs",
        "repos_url": "https://api.github.com/users/kevbost/repos",
        "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kevbost/received_events",
        "type": "User",
        "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kevbost/kb-scss-thirty-examples-rewrite",
    "description": "Rewriting the Thirty CSS Examples HW in SCSS",
    "fork": false,
    "url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite",
    "forks_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/forks",
    "keys_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/teams",
    "hooks_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/hooks",
    "issue_events_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/events",
    "assignees_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/tags",
    "blobs_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/languages",
    "stargazers_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/stargazers",
    "contributors_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/contributors",
    "subscribers_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/subscribers",
    "subscription_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/subscription",
    "commits_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/merges",
    "archive_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/downloads",
    "issues_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/labels{/name}",
    "releases_url": "https://api.github.com/repos/kevbost/kb-scss-thirty-examples-rewrite/releases{/id}",
    "created_at": "2014-05-05T17:22:33Z",
    "updated_at": "2014-05-07T04:58:10Z",
    "pushed_at": "2014-05-07T04:58:09Z",
    "git_url": "git://github.com/kevbost/kb-scss-thirty-examples-rewrite.git",
    "ssh_url": "git@github.com:kevbost/kb-scss-thirty-examples-rewrite.git",
    "clone_url": "https://github.com/kevbost/kb-scss-thirty-examples-rewrite.git",
    "svn_url": "https://github.com/kevbost/kb-scss-thirty-examples-rewrite",
    "homepage": null,
    "size": 7896,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
}];





var userApi = [{
    "login": "kevbost",
    "id": 1672548,
    "avatar_url": "https://avatars.githubusercontent.com/u/1672548?",
    "gravatar_id": "6fec2506d8b1f2ca9f3cc4202fd9fc7c",
    "url": "https://api.github.com/users/kevbost",
    "html_url": "https://github.com/kevbost",
    "followers_url": "https://api.github.com/users/kevbost/followers",
    "following_url": "https://api.github.com/users/kevbost/following{/other_user}",
    "gists_url": "https://api.github.com/users/kevbost/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kevbost/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kevbost/subscriptions",
    "organizations_url": "https://api.github.com/users/kevbost/orgs",
    "repos_url": "https://api.github.com/users/kevbost/repos",
    "events_url": "https://api.github.com/users/kevbost/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kevbost/received_events",
    "type": "User",
    "site_admin": false,
    "namex": "Kevin Bost",
    "company": "",
    "blog": "www.kevinbost.com",
    "location": "United States",
    "email": "kevbost@gmail.com",
    "hireable": false,
    "bio": null,
    "public_repos": 8,
    "public_gists": 1,
    "followers": 4,
    "following": 1,
    "created_at": "2012-04-23T22:23:11Z",
    "updated_at": "2014-05-14T06:56:54Z"
}];

var logoIcon = '<div class="logoIcon"></div><div class="notifications"></div><div class="nav"></div>';
$('.headContainer').append(logoIcon);

var navLeft = '<div class="searchBar"></div><ul class="navLeft"><h4><li>Explore</li><li>Gist</li><li>Blog</li><li>Help</li></h4></ul>';
$('.nav').append(navLeft);

var navRight = '<ul class="navRight"><h1><li>✣</li><li>⬅</li><li>↳</li></h1></ul>';
$('.nav').append(navRight);

var main = '<div class="main"></div>';
$('.container').append(main);

var sideBar = '<div class="sideBar"></div>';
$('.container').prepend(sideBar);

var profileImage = '<div class="profileImage"></div>';
$('.sideBar').append(profileImage);

var tabs = '<div class="tabs"><div class="tabs"></div><div class="reposTitle"></div><div class="reposRight"></div></div>';
$('.main').append(tabs);

var repos = '<div class="repos"><div class="reposLeft"></div><div class="reposTitle"></div><div class="reposRight"></div></div>';
$('.main').append(repos);


// // ====
// // Dill
// // ====

// var numStarred = 0;

// repoApi.forEach(function(repo) {
//     numStarred = numStarred + repo.stargazers_count;
// });

// userApi[0].starred = numStarred;



// var test = repos.owner.length();
// $('body').append(test);
// var anyways = _.reposGit.url;
// anyways.map(function(x) {
// 	console.log(x);
// });

// // repos.url.map(function(x) {
// // 	console.log(x);
// // });



// // ============
// // Mason's Gist
// // ============

// var people = [{
//     person: 'Mason',
//     feeling: 'great'
// }, {
//     person: 'Bob',
//     feeling: 'terrible'
// }];

// //  function              function       string  
// var goodMorningTemplate = _.template($('.goodmorning-template').text());
// people.forEach(function(person) {

//     //    string       function             object
//     var rendered = goodMorningTemplate(person);

//     $('body').prepend(rendered);
// });


// ========
// My Notes
// ========

// //function                 function         string
// var goodMorningTemplate = _.template($('Goodmorning, <%= person %>.').text());

// // string                     function        object (literal)
// var morningJuniper = goodMorningTemplate({person: 'Juniper'});
// var morningKevin = goodMorningTemplate({  person: 'Kevin',
// 										  feeling: 'great'
// });

// // function     string
// console.log(morningKevin);

// // push it to the browser
// $('body').prepend(morningKevin);


// var people = [
// 	{
// 		person: 'Kevin',
// 		feeling: 'Awesome'
// 	}
// ];